sudo: false
language: node_js
os:
  - linux
  - osx
dist: xenial
addons:
  apt:
    packages:
      - yasm
  homebrew:
    packages:
      - yasm
node_js:
  - v12
  - v10
  - v8
before_install:
  - export ASM_NASM=$(which yasm)
