#include <nan.h>
#include <turbojpeg.h>

enum {
  FORMAT_RGB  = TJPF_RGB,
  FORMAT_BGR  = TJPF_BGR,
  FORMAT_RGBX = TJPF_RGBX,
  FORMAT_BGRX = TJPF_BGRX,
  FORMAT_XRGB = TJPF_XRGB,
  FORMAT_XBGR = TJPF_XBGR,
  FORMAT_GRAY = TJPF_GRAY,
  FORMAT_RGBA = TJPF_RGBA,
  FORMAT_BGRA = TJPF_BGRA,
  FORMAT_ABGR = TJPF_ABGR,
  FORMAT_ARGB = TJPF_ARGB,
};

NAN_METHOD(DecompressSync);
